### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Busybody64** [Perodactyl/w93appMan#2]
How do I get the notifications that appear in the taskbar to work?

**Comment by Perodactyl** [comment]
What do you mean?

**Comment by Busybody64** [comment]
Like the little yellow popups that appear in the bottom right corner of the screen when it installs (and tells you how to open it)

**Comment by Perodactyl** [comment]
I just fixed that. It was appearing while the boot screen was shown, while the user couldn't see it.
